/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const REMOVE_OPERATOR_DISCRIMINATOR = 5;

export function getRemoveOperatorDiscriminatorBytes() {
  return getU8Encoder().encode(REMOVE_OPERATOR_DISCRIMINATOR);
}

export type RemoveOperatorInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountOperator extends string | IAccountMeta<string> = string,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TAccountSnapshot extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountOperator extends string
        ? ReadonlyAccount<TAccountOperator>
        : TAccountOperator,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountSnapshot extends string
        ? WritableAccount<TAccountSnapshot>
        : TAccountSnapshot,
      ...TRemainingAccounts,
    ]
  >;

export type RemoveOperatorInstructionData = { discriminator: number };

export type RemoveOperatorInstructionDataArgs = {};

export function getRemoveOperatorInstructionDataEncoder(): Encoder<RemoveOperatorInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: REMOVE_OPERATOR_DISCRIMINATOR })
  );
}

export function getRemoveOperatorInstructionDataDecoder(): Decoder<RemoveOperatorInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getRemoveOperatorInstructionDataCodec(): Codec<
  RemoveOperatorInstructionDataArgs,
  RemoveOperatorInstructionData
> {
  return combineCodec(
    getRemoveOperatorInstructionDataEncoder(),
    getRemoveOperatorInstructionDataDecoder()
  );
}

export type RemoveOperatorInput<
  TAccountConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountOperator extends string = string,
  TAccountAdmin extends string = string,
  TAccountSnapshot extends string = string,
> = {
  config: Address<TAccountConfig>;
  ncn: Address<TAccountNcn>;
  operator: Address<TAccountOperator>;
  admin: TransactionSigner<TAccountAdmin>;
  snapshot: Address<TAccountSnapshot>;
};

export function getRemoveOperatorInstruction<
  TAccountConfig extends string,
  TAccountNcn extends string,
  TAccountOperator extends string,
  TAccountAdmin extends string,
  TAccountSnapshot extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: RemoveOperatorInput<
    TAccountConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountAdmin,
    TAccountSnapshot
  >,
  config?: { programAddress?: TProgramAddress }
): RemoveOperatorInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountNcn,
  TAccountOperator,
  TAccountAdmin,
  TAccountSnapshot
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    ncn: { value: input.ncn ?? null, isWritable: false },
    operator: { value: input.operator ?? null, isWritable: false },
    admin: { value: input.admin ?? null, isWritable: false },
    snapshot: { value: input.snapshot ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.snapshot),
    ],
    programAddress,
    data: getRemoveOperatorInstructionDataEncoder().encode({}),
  } as RemoveOperatorInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountAdmin,
    TAccountSnapshot
  >;

  return instruction;
}

export type ParsedRemoveOperatorInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    ncn: TAccountMetas[1];
    operator: TAccountMetas[2];
    admin: TAccountMetas[3];
    snapshot: TAccountMetas[4];
  };
  data: RemoveOperatorInstructionData;
};

export function parseRemoveOperatorInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedRemoveOperatorInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      ncn: getNextAccount(),
      operator: getNextAccount(),
      admin: getNextAccount(),
      snapshot: getNextAccount(),
    },
    data: getRemoveOperatorInstructionDataDecoder().decode(instruction.data),
  };
}
