/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const VERIFY_CERTIFICATE_DISCRIMINATOR = 10;

export function getVerifyCertificateDiscriminatorBytes() {
  return getU8Encoder().encode(VERIFY_CERTIFICATE_DISCRIMINATOR);
}

export type VerifyCertificateInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountNcnConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountSnapshot extends string | IAccountMeta<string> = string,
  TAccountRestakingConfig extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountNcnConfig extends string
        ? ReadonlyAccount<TAccountNcnConfig>
        : TAccountNcnConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountSnapshot extends string
        ? ReadonlyAccount<TAccountSnapshot>
        : TAccountSnapshot,
      TAccountRestakingConfig extends string
        ? ReadonlyAccount<TAccountRestakingConfig>
        : TAccountRestakingConfig,
      ...TRemainingAccounts,
    ]
  >;

export type VerifyCertificateInstructionData = {
  discriminator: number;
  digest: ReadonlyUint8Array;
  aggregatedG2: ReadonlyUint8Array;
  aggregatedSignature: ReadonlyUint8Array;
  operatorsSignatureBitmap: ReadonlyUint8Array;
  expectedGeneration: bigint;
};

export type VerifyCertificateInstructionDataArgs = {
  digest: ReadonlyUint8Array;
  aggregatedG2: ReadonlyUint8Array;
  aggregatedSignature: ReadonlyUint8Array;
  operatorsSignatureBitmap: ReadonlyUint8Array;
  expectedGeneration: number | bigint;
};

export function getVerifyCertificateInstructionDataEncoder(): Encoder<VerifyCertificateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['digest', fixEncoderSize(getBytesEncoder(), 32)],
      ['aggregatedG2', fixEncoderSize(getBytesEncoder(), 64)],
      ['aggregatedSignature', fixEncoderSize(getBytesEncoder(), 32)],
      [
        'operatorsSignatureBitmap',
        addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
      ],
      ['expectedGeneration', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: VERIFY_CERTIFICATE_DISCRIMINATOR })
  );
}

export function getVerifyCertificateInstructionDataDecoder(): Decoder<VerifyCertificateInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['digest', fixDecoderSize(getBytesDecoder(), 32)],
    ['aggregatedG2', fixDecoderSize(getBytesDecoder(), 64)],
    ['aggregatedSignature', fixDecoderSize(getBytesDecoder(), 32)],
    [
      'operatorsSignatureBitmap',
      addDecoderSizePrefix(getBytesDecoder(), getU32Decoder()),
    ],
    ['expectedGeneration', getU64Decoder()],
  ]);
}

export function getVerifyCertificateInstructionDataCodec(): Codec<
  VerifyCertificateInstructionDataArgs,
  VerifyCertificateInstructionData
> {
  return combineCodec(
    getVerifyCertificateInstructionDataEncoder(),
    getVerifyCertificateInstructionDataDecoder()
  );
}

export type VerifyCertificateInput<
  TAccountNcnConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountSnapshot extends string = string,
  TAccountRestakingConfig extends string = string,
> = {
  ncnConfig: Address<TAccountNcnConfig>;
  ncn: Address<TAccountNcn>;
  snapshot: Address<TAccountSnapshot>;
  restakingConfig: Address<TAccountRestakingConfig>;
  digest: VerifyCertificateInstructionDataArgs['digest'];
  aggregatedG2: VerifyCertificateInstructionDataArgs['aggregatedG2'];
  aggregatedSignature: VerifyCertificateInstructionDataArgs['aggregatedSignature'];
  operatorsSignatureBitmap: VerifyCertificateInstructionDataArgs['operatorsSignatureBitmap'];
  expectedGeneration: VerifyCertificateInstructionDataArgs['expectedGeneration'];
};

export function getVerifyCertificateInstruction<
  TAccountNcnConfig extends string,
  TAccountNcn extends string,
  TAccountSnapshot extends string,
  TAccountRestakingConfig extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: VerifyCertificateInput<
    TAccountNcnConfig,
    TAccountNcn,
    TAccountSnapshot,
    TAccountRestakingConfig
  >,
  config?: { programAddress?: TProgramAddress }
): VerifyCertificateInstruction<
  TProgramAddress,
  TAccountNcnConfig,
  TAccountNcn,
  TAccountSnapshot,
  TAccountRestakingConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    ncnConfig: { value: input.ncnConfig ?? null, isWritable: false },
    ncn: { value: input.ncn ?? null, isWritable: false },
    snapshot: { value: input.snapshot ?? null, isWritable: false },
    restakingConfig: {
      value: input.restakingConfig ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.ncnConfig),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.snapshot),
      getAccountMeta(accounts.restakingConfig),
    ],
    programAddress,
    data: getVerifyCertificateInstructionDataEncoder().encode(
      args as VerifyCertificateInstructionDataArgs
    ),
  } as VerifyCertificateInstruction<
    TProgramAddress,
    TAccountNcnConfig,
    TAccountNcn,
    TAccountSnapshot,
    TAccountRestakingConfig
  >;

  return instruction;
}

export type ParsedVerifyCertificateInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    ncnConfig: TAccountMetas[0];
    ncn: TAccountMetas[1];
    snapshot: TAccountMetas[2];
    restakingConfig: TAccountMetas[3];
  };
  data: VerifyCertificateInstructionData;
};

export function parseVerifyCertificateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedVerifyCertificateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      ncnConfig: getNextAccount(),
      ncn: getNextAccount(),
      snapshot: getNextAccount(),
      restakingConfig: getNextAccount(),
    },
    data: getVerifyCertificateInstructionDataDecoder().decode(instruction.data),
  };
}
