/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';
import {
  getStakeWeightsDecoder,
  getStakeWeightsEncoder,
  type StakeWeights,
  type StakeWeightsArgs,
} from '.';

export type VaultContribution = {
  registrySlot: bigint;
  stakeWeight: StakeWeights;
  nextEpochStakeWeight: StakeWeights;
};

export type VaultContributionArgs = {
  registrySlot: number | bigint;
  stakeWeight: StakeWeightsArgs;
  nextEpochStakeWeight: StakeWeightsArgs;
};

export function getVaultContributionEncoder(): Encoder<VaultContributionArgs> {
  return getStructEncoder([
    ['registrySlot', getU64Encoder()],
    ['stakeWeight', getStakeWeightsEncoder()],
    ['nextEpochStakeWeight', getStakeWeightsEncoder()],
  ]);
}

export function getVaultContributionDecoder(): Decoder<VaultContribution> {
  return getStructDecoder([
    ['registrySlot', getU64Decoder()],
    ['stakeWeight', getStakeWeightsDecoder()],
    ['nextEpochStakeWeight', getStakeWeightsDecoder()],
  ]);
}

export function getVaultContributionCodec(): Codec<
  VaultContributionArgs,
  VaultContribution
> {
  return combineCodec(
    getVaultContributionEncoder(),
    getVaultContributionDecoder()
  );
}
